#ifndef PID_WRAPPER_H
#define PID_WRAPPER_H

/* Thin C-callable shim around PIDController.hpp -- see rpi_camera_system's
 * CLAUDE.md for why this lives in its own .cpp/.hpp pair instead of
 * converting the whole otherwise-pure-C project to C++: this firmware's
 * build (a plain arm-none-eabi-gcc-driven Makefile generated by CubeIDE)
 * has no C++ awareness at all, and this project has already been burned
 * once by a CubeMX regeneration silently reverting hand-added settings --
 * a project-wide language-mode change was judged too large a blast
 * radius for what's really a one-class addition.
 *
 * All PID math lives in PIDController.hpp; this file/its .cpp just owns
 * one instance and forwards calls so main.c (still plain C) can drive
 * it. setpoint/measurement are real pixel values (already divided by
 * POSITION_SCALE). The return value is a CORRECTION relative to
 * whatever base_dac_y the caller is using for bumpless transfer, not an
 * absolute DAC value -- main.c adds its own base and does the final
 * [DAC_MIN_COUNT, DAC_MAX_COUNT] hardware clamp via apply_dac(), exactly
 * as it did before this change. That bumpless-transfer/final-clamp
 * design is this firmware's own control architecture, not something
 * PIDController.hpp provides or needs to know about.
 *
 * PIDController.hpp was originally used byte-for-byte per Phil's e-mail
 * (2026-08-18), with ts_s fixed at pid_wrapper_init() and never varying
 * per call -- a real, identified problem: this firmware's control loop
 * fires on telemetry ARRIVAL (irregular), not a fixed hardware timer, so
 * a constant assumed ts_ silently mis-weights the integral/derivative
 * whenever the real inter-call interval differs from it (confirmed via
 * direct jitter measurement, see CLAUDE.md -- full-rate CV ~71%,
 * throttled ~44%, neither a clean metronome). **2026-08-19: minimally
 * modified PIDController.hpp to accept a real per-call dt** (see that
 * file's own docstring for the exact change -- same P/I/D terms, same
 * anti-windup, same filter design, only the timing math changed) rather
 * than switching to a different library, since the algorithm itself
 * (already extensively tuned against this session) doesn't need to
 * change, only its timing assumption. ts_s (pid_wrapper_init's argument,
 * still live-settable via pid_wrapper_set_ts) is now only the
 * construction-time FALLBACK for a dt<=0 call (e.g. the first call after
 * (re)construction) -- main.c's run_closed_loop_step measures real dt via
 * HAL_GetTick() and passes it to every pid_wrapper_calculate() call. */

#ifdef __cplusplus
extern "C" {
#endif

void   pid_wrapper_init(double kp, double ki, double kd, double ts_s, double fc_hz,
                         double out_min, double out_max);
void   pid_wrapper_set_gains(double kp, double ki, double kd);
void   pid_wrapper_set_fc(double fc_hz);  /* derivative low-pass cutoff, live-settable -- see
                                            * the g_fc_hz comment in pid_wrapper.cpp for why this
                                            * was added (20Hz default found too high relative to
                                            * this rig's ~15.3Hz resonance) */
void   pid_wrapper_set_ts(double ts_s);  /* live-settable sample time, see pid_wrapper.cpp --
                                            * added 2026-08-19 to test control-rate-throttling
                                            * hypotheses without a reflash per attempt */
void   pid_wrapper_set_out_limits(double out_min, double out_max);  /* live-settable output
                                            * saturation range passed straight to
                                            * PIDController::setOutputLimits() -- added 2026-08-19
                                            * to test whether tightening this (originally set to
                                            * the full +-DAC-span, so back-calculation anti-windup
                                            * never engages for a normal-sized correction) recovers
                                            * some of the settling-time/overshoot regression found
                                            * after adopting this class vs. the old hand-rolled
                                            * controller's proactive integral clamp -- see CLAUDE.md */
double pid_wrapper_calculate(double setpoint_px, double measurement_px, double dt_s);
                                            /* dt_s: real elapsed seconds since the caller's own
                                            * last control step (<=0 to fall back to ts_) -- see
                                            * this header's own docstring above, 2026-08-19 */
double pid_wrapper_calculate2(double setpoint_px, double measurement_px, double dt_s);
                                            /* second axis (dac_x <- cy), identical Kp/Ki/Kd/ts_s/
                                            * fc_hz/limits to the first (reconstructed together by
                                            * every gain/fc/ts/limit setter) but its own independent
                                            * integral/derivative history -- added 2026-08-19 */
void   pid_wrapper_reset(void);  /* resets BOTH axes' integral/derivative history together */

#ifdef __cplusplus
}
#endif

#endif /* PID_WRAPPER_H */
