#ifndef PID_WRAPPER_H
#define PID_WRAPPER_H

/* Thin C-callable shim around PIDController.hpp (used completely
 * unmodified, per Phil's e-mail, 2026-08-18 -- see rpi_camera_system's
 * CLAUDE.md for why this lives in its own .cpp/.hpp pair instead of
 * converting the whole otherwise-pure-C project to C++: this firmware's
 * build (a plain arm-none-eabi-gcc-driven Makefile generated by CubeIDE)
 * has no C++ awareness at all, and this project has already been burned
 * once by a CubeMX regeneration silently reverting hand-added settings --
 * a project-wide language-mode change was judged too large a blast
 * radius for what's really a one-class addition.
 *
 * All PID math lives in PIDController.hpp; this file/its .cpp just owns
 * one instance and forwards calls so main.c (still plain C) can drive
 * it. setpoint/measurement are real pixel values (already divided by
 * POSITION_SCALE). The return value is a CORRECTION relative to
 * whatever base_dac_y the caller is using for bumpless transfer, not an
 * absolute DAC value -- main.c adds its own base and does the final
 * [DAC_MIN_COUNT, DAC_MAX_COUNT] hardware clamp via apply_dac(), exactly
 * as it did before this change. That bumpless-transfer/final-clamp
 * design is this firmware's own control architecture, not something
 * PIDController.hpp provides or needs to know about.
 *
 * ts_s is fixed at pid_wrapper_init() and never varies per call --
 * PIDController.hpp's calculate() takes no dt argument at all (ts_ is
 * baked in at construction), unlike this firmware's PREVIOUS hand-rolled
 * control step, which measured a real, slightly-variable dt every call
 * via HAL_GetTick(). Using this class as given means accepting a fixed-
 * ts_ approximation instead -- a known, deliberate consequence of
 * adopting the class unmodified, not an oversight. ts_s should be set to
 * this firmware's typical closed-loop telemetry-driven control rate
 * (measured ~207-216Hz across this project's 2026-08-13/14 tuning
 * sessions, i.e. ts_s ~= 1/210). */

#ifdef __cplusplus
extern "C" {
#endif

void   pid_wrapper_init(double kp, double ki, double kd, double ts_s, double fc_hz,
                         double out_min, double out_max);
void   pid_wrapper_set_gains(double kp, double ki, double kd);
void   pid_wrapper_set_fc(double fc_hz);  /* derivative low-pass cutoff, live-settable -- see
                                            * the g_fc_hz comment in pid_wrapper.cpp for why this
                                            * was added (20Hz default found too high relative to
                                            * this rig's ~15.3Hz resonance) */
double pid_wrapper_calculate(double setpoint_px, double measurement_px);
void   pid_wrapper_reset(void);

#ifdef __cplusplus
}
#endif

#endif /* PID_WRAPPER_H */
